spring:
  application:
    name: FoxWearManagement
  datasource:
    username: rgb
    password: foxwear
    url: jdbc:postgresql://localhost:5432/foxweardb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8050